### PR TITLE
Expose `liftBase` function

### LINKED ISSUE #3: Allow Byline to be used within other transformer stacks
Is there a specific design reason for not implementing `MonadTrans` or exposing `liftBase`? My use case is, I think, a common one: use `byline` as an interface to read, modify, and interact with a much more complicated datatype within a `StateT` transformer.

Specifically, my app looks like `type App = ReaderT AppConfig (StateT AppState IO)`. At some point after gathering configuration and setting up initial state, I'd like to `runPrompt :: App ()` where
```haskell
runPrompt :: App ()
runPrompt = runByline $ do
  app_state <- get
  -- or
  app_state <- liftBase get
  sayLn $ "Here's something specific from my app state" <> render app_state
```

Am I missing something? Is there already a way to do this? Let me know what you think. Thanks!

### PR DESCRIPTION
**Pull request by samtay**
Quick one for ya. Closes #3

### CODE REVIEW

**Comment by pjones** [comment]
If we are going to export this, does the name `liftBase` make sense?  Is there an existing name (or even a function from `MonadTrans`) that makes more sense?

**Comment by samtay** [comment]
Yeah so.. I think this is a standard `lift :: (MonadTrans t, Monad m) => m a -> t m a`, and I've updated the PR. That being said, this is kind of my first foray into monad transformers, so I'm not 100% sure. What do you think? For what it's worth, with these changes my function `f :: Byline App a` works as expected, allowing me to get my app state via `appState <- lift get`.

**Comment by samtay** [comment]
(FYI tried to add `MonadTrans` to the deriving clause, but compiler couldn't handle it.)

**Comment by pjones** [comment]
Let me see if I can get `MonadTrans` working.  That might be the best option.

**Comment by samtay** [comment]
Like I said, the `MonadTrans` instance I have written here works for me.
Feel free to test it out and let me know what you think.

On Jul 19, 2017 4:00 PM, "Peter J. Jones" <notifications@github.com> wrote:

Let me see if I can get MonadTrans working. That might be the best option.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pjones/byline/pull/4#issuecomment-316499582>, or mute
the thread

**Comment by pjones** [comment]
Oh, I don't know how I missed that.  Sorry.  Thanks for all your help!

**Pull request merged**
